### PR TITLE
Feature/acid

### PR DESCRIPTION
**Pull request by kj187**
http://dev.targetprocess.com/rest/getting_started#all_for_project

### CODE REVIEW

**Comment by 8bitDesigner** [comment]
Two things:
1. You're setting the context for every request and as part of the initializer. Since I don't use Target Process much these days, I may not be an expert, but I could theoretically see the idea of using the same client instance with two different contexts:

``` javascript
const tp = require('tp-api')({ ... })
const firstRequest = tp('Tasks').context('foo').then(function() { ... })
const secondRequest = tp('Tasks').context('bar').then(function() { ... })
```
1. That said, I'm not using Target Process much these days - would you like contributor access to free you up to merge your own changes against this repo?

**Comment by kj187** [comment]
1) I will check that

second 1) ;-)
Yes sure, if that is ok for you

**Comment by 8bitDesigner** [comment]
Dig it, you're added! Feel free to merge when you think it's ready. Also, if you hit me back with your NPM username, I'll add you as a contributor there, which will let you publish a new version of the module as well.

**Comment by kj187** [comment]
Nice! My NPM account is kj187 
https://www.npmjs.com/~kj187

**Pull request merged**
